-- =============================================================================
-- TechMood — 0029 Fields and Interests catalogues
--
-- One hundred fields and fifty-three interests, all `approved`. They are
-- configuration, not content: the platform ships with a list so onboarding is
-- a search rather than a blank box, and members extend it through
-- suggest_taxonomy_term(), which files a term for review instead of adding it.
--
-- Fields and interests are kept apart on purpose. A field is where you work
-- (matching reads it, and you may hold at most three). An interest is what you
-- care about (recommendations read it, and there is no limit). Skills, in the
-- table next door, are what you can do, and evidence can verify them.
-- =============================================================================

insert into public.fields (slug, name_ar, name_en) values
  ('software-engineering', 'هندسة البرمجيات', 'Software Engineering'),
  ('frontend-development', 'تطوير الواجهات الأمامية', 'Frontend Development'),
  ('backend-development', 'تطوير الأنظمة الخلفية', 'Backend Development'),
  ('fullstack-development', 'التطوير الشامل', 'Full-Stack Development'),
  ('mobile-development', 'تطوير تطبيقات الجوال', 'Mobile Development'),
  ('ios-development', 'تطوير iOS', 'iOS Development'),
  ('android-development', 'تطوير Android', 'Android Development'),
  ('cross-platform-development', 'التطوير متعدد المنصات', 'Cross-Platform Development'),
  ('web-design', 'تصميم الويب', 'Web Design'),
  ('ui-design', 'تصميم واجهات المستخدم', 'UI Design'),
  ('ux-design', 'تصميم تجربة المستخدم', 'UX Design'),
  ('ux-research', 'بحوث تجربة المستخدم', 'UX Research'),
  ('graphic-design', 'التصميم الجرافيكي', 'Graphic Design'),
  ('motion-design', 'تصميم الموشن', 'Motion Design'),
  ('brand-design', 'تصميم الهوية البصرية', 'Brand Design'),
  ('product-design', 'تصميم المنتجات', 'Product Design'),
  ('product-management', 'إدارة المنتجات', 'Product Management'),
  ('project-management', 'إدارة المشاريع', 'Project Management'),
  ('agile-scrum', 'أجايل وسكرم', 'Agile & Scrum'),
  ('business-analysis', 'تحليل الأعمال', 'Business Analysis'),
  ('data-analysis', 'تحليل البيانات', 'Data Analysis'),
  ('data-engineering', 'هندسة البيانات', 'Data Engineering'),
  ('data-science', 'علم البيانات', 'Data Science'),
  ('machine-learning', 'تعلّم الآلة', 'Machine Learning'),
  ('deep-learning', 'التعلّم العميق', 'Deep Learning'),
  ('generative-ai', 'الذكاء الاصطناعي التوليدي', 'Generative AI'),
  ('nlp', 'معالجة اللغة الطبيعية', 'Natural Language Processing'),
  ('computer-vision', 'الرؤية الحاسوبية', 'Computer Vision'),
  ('mlops', 'هندسة تشغيل النماذج', 'MLOps'),
  ('business-intelligence', 'ذكاء الأعمال', 'Business Intelligence'),
  ('data-visualization', 'تصوير البيانات', 'Data Visualization'),
  ('big-data', 'البيانات الضخمة', 'Big Data'),
  ('database-administration', 'إدارة قواعد البيانات', 'Database Administration'),
  ('cloud-computing', 'الحوسبة السحابية', 'Cloud Computing'),
  ('aws', 'منصة AWS', 'Amazon Web Services'),
  ('azure', 'منصة Azure', 'Microsoft Azure'),
  ('google-cloud', 'منصة Google Cloud', 'Google Cloud Platform'),
  ('devops', 'هندسة DevOps', 'DevOps'),
  ('site-reliability', 'هندسة موثوقية الأنظمة', 'Site Reliability Engineering'),
  ('platform-engineering', 'هندسة المنصات', 'Platform Engineering'),
  ('containers-kubernetes', 'الحاويات وKubernetes', 'Containers & Kubernetes'),
  ('infrastructure-as-code', 'البنية التحتية ككود', 'Infrastructure as Code'),
  ('ci-cd', 'التكامل والنشر المستمر', 'CI/CD'),
  ('cybersecurity', 'الأمن السيبراني', 'Cybersecurity'),
  ('application-security', 'أمن التطبيقات', 'Application Security'),
  ('network-security', 'أمن الشبكات', 'Network Security'),
  ('penetration-testing', 'اختبار الاختراق', 'Penetration Testing'),
  ('digital-forensics', 'التحقيق الجنائي الرقمي', 'Digital Forensics'),
  ('grc', 'الحوكمة والمخاطر والامتثال', 'Governance, Risk & Compliance'),
  ('networking', 'الشبكات', 'Networking'),
  ('systems-administration', 'إدارة الأنظمة', 'Systems Administration'),
  ('it-support', 'الدعم الفني', 'IT Support'),
  ('qa-testing', 'ضمان الجودة والاختبار', 'QA & Testing'),
  ('test-automation', 'أتمتة الاختبارات', 'Test Automation'),
  ('performance-engineering', 'هندسة الأداء', 'Performance Engineering'),
  ('technical-writing', 'الكتابة التقنية', 'Technical Writing'),
  ('developer-relations', 'علاقات المطوّرين', 'Developer Relations'),
  ('game-development', 'تطوير الألعاب', 'Game Development'),
  ('game-design', 'تصميم الألعاب', 'Game Design'),
  ('3d-modeling', 'النمذجة ثلاثية الأبعاد', '3D Modeling'),
  ('ar-vr', 'الواقع المعزّز والافتراضي', 'AR & VR'),
  ('embedded-systems', 'الأنظمة المدمجة', 'Embedded Systems'),
  ('iot', 'إنترنت الأشياء', 'Internet of Things'),
  ('robotics', 'الروبوتات', 'Robotics'),
  ('electronics', 'الإلكترونيات', 'Electronics'),
  ('hardware-engineering', 'هندسة العتاد', 'Hardware Engineering'),
  ('blockchain', 'البلوك تشين', 'Blockchain'),
  ('web3', 'ويب3', 'Web3'),
  ('fintech', 'التقنية المالية', 'Fintech'),
  ('e-commerce', 'التجارة الإلكترونية', 'E-Commerce'),
  ('edtech', 'تقنية التعليم', 'EdTech'),
  ('healthtech', 'التقنية الصحية', 'HealthTech'),
  ('agritech', 'التقنية الزراعية', 'AgriTech'),
  ('govtech', 'التقنية الحكومية', 'GovTech'),
  ('digital-marketing', 'التسويق الرقمي', 'Digital Marketing'),
  ('seo', 'تحسين محركات البحث', 'SEO'),
  ('content-marketing', 'تسويق المحتوى', 'Content Marketing'),
  ('social-media', 'إدارة وسائل التواصل', 'Social Media Management'),
  ('growth-marketing', 'تسويق النمو', 'Growth Marketing'),
  ('copywriting', 'كتابة المحتوى الإعلاني', 'Copywriting'),
  ('content-creation', 'صناعة المحتوى', 'Content Creation'),
  ('video-production', 'إنتاج الفيديو', 'Video Production'),
  ('photography', 'التصوير الفوتوغرافي', 'Photography'),
  ('audio-production', 'الإنتاج الصوتي', 'Audio Production'),
  ('translation', 'الترجمة', 'Translation'),
  ('entrepreneurship', 'ريادة الأعمال', 'Entrepreneurship'),
  ('startup-strategy', 'استراتيجية الشركات الناشئة', 'Startup Strategy'),
  ('venture-fundraising', 'جمع التمويل', 'Venture Fundraising'),
  ('sales', 'المبيعات', 'Sales'),
  ('customer-success', 'نجاح العملاء', 'Customer Success'),
  ('operations', 'العمليات', 'Operations'),
  ('finance-accounting', 'المالية والمحاسبة', 'Finance & Accounting'),
  ('human-resources', 'الموارد البشرية', 'Human Resources'),
  ('legal-tech', 'التقنية القانونية', 'Legal Tech'),
  ('teaching-training', 'التدريب والتعليم', 'Teaching & Training'),
  ('career-coaching', 'الإرشاد المهني', 'Career Coaching'),
  ('research', 'البحث العلمي', 'Research'),
  ('software-architecture', 'هندسة معمارية البرمجيات', 'Software Architecture'),
  ('api-design', 'تصميم واجهات البرمجة', 'API Design'),
  ('accessibility', 'إتاحة الوصول', 'Accessibility')
on conflict (slug) do nothing;

insert into public.interests (slug, name_ar, name_en) values
  ('open-source', 'المصادر المفتوحة', 'Open Source'),
  ('hackathons', 'الهاكاثونات', 'Hackathons'),
  ('competitive-programming', 'البرمجة التنافسية', 'Competitive Programming'),
  ('ctf', 'مسابقات الأمن CTF', 'Capture The Flag'),
  ('side-projects', 'المشاريع الجانبية', 'Side Projects'),
  ('freelancing', 'العمل الحر', 'Freelancing'),
  ('remote-work', 'العمل عن بُعد', 'Remote Work'),
  ('mentoring', 'الإرشاد والتوجيه', 'Mentoring'),
  ('public-speaking', 'التحدّث أمام الجمهور', 'Public Speaking'),
  ('tech-communities', 'المجتمعات التقنية', 'Tech Communities'),
  ('meetups', 'اللقاءات التقنية', 'Meetups'),
  ('conferences', 'المؤتمرات', 'Conferences'),
  ('blogging', 'التدوين', 'Blogging'),
  ('podcasting', 'البودكاست', 'Podcasting'),
  ('newsletters', 'النشرات البريدية', 'Newsletters'),
  ('reading-tech', 'القراءة التقنية', 'Tech Reading'),
  ('research-papers', 'الأوراق البحثية', 'Research Papers'),
  ('ai-ethics', 'أخلاقيات الذكاء الاصطناعي', 'AI Ethics'),
  ('privacy', 'الخصوصية الرقمية', 'Digital Privacy'),
  ('digital-rights', 'الحقوق الرقمية', 'Digital Rights'),
  ('accessibility-advocacy', 'الدفاع عن إتاحة الوصول', 'Accessibility Advocacy'),
  ('sustainability', 'الاستدامة', 'Sustainability'),
  ('climate-tech', 'تقنيات المناخ', 'Climate Tech'),
  ('social-impact', 'الأثر الاجتماعي', 'Social Impact'),
  ('nonprofit-tech', 'تقنية المؤسسات غير الربحية', 'Nonprofit Tech'),
  ('arabic-tech', 'المحتوى التقني العربي', 'Arabic Tech Content'),
  ('localization', 'التعريب والتوطين', 'Localization'),
  ('design-systems', 'أنظمة التصميم', 'Design Systems'),
  ('typography', 'الخطوط والطباعة', 'Typography'),
  ('illustration', 'الرسم التوضيحي', 'Illustration'),
  ('animation', 'الرسوم المتحركة', 'Animation'),
  ('music', 'الموسيقى', 'Music'),
  ('gaming', 'الألعاب', 'Gaming'),
  ('esports', 'الرياضات الإلكترونية', 'Esports'),
  ('board-games', 'ألعاب الطاولة', 'Board Games'),
  ('chess', 'الشطرنج', 'Chess'),
  ('sports', 'الرياضة', 'Sports'),
  ('fitness', 'اللياقة البدنية', 'Fitness'),
  ('travel', 'السفر', 'Travel'),
  ('photography-hobby', 'التصوير كهواية', 'Photography (Hobby)'),
  ('cooking', 'الطبخ', 'Cooking'),
  ('volunteering', 'العمل التطوعي', 'Volunteering'),
  ('teaching-kids', 'تعليم الأطفال البرمجة', 'Teaching Kids to Code'),
  ('women-in-tech', 'المرأة في التقنية', 'Women in Tech'),
  ('career-switching', 'تغيير المسار المهني', 'Career Switching'),
  ('first-job', 'الوظيفة الأولى', 'First Job'),
  ('internships', 'التدريب العملي', 'Internships'),
  ('scholarships', 'المنح الدراسية', 'Scholarships'),
  ('startup-news', 'أخبار الشركات الناشئة', 'Startup News'),
  ('investing', 'الاستثمار', 'Investing'),
  ('productivity', 'الإنتاجية', 'Productivity'),
  ('personal-branding', 'العلامة الشخصية', 'Personal Branding'),
  ('language-learning', 'تعلّم اللغات', 'Language Learning')
on conflict (slug) do nothing;
